# POST article (private)
POST /api/v2/items HTTP/1.1
Host: {{host}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "body": "# Example\n\ntesing\n\n## h2\n\n- hoge\n\n- fuga\n\n### h3\n\n1. foo\n\n1. bar\n\n#### h4\n\n##### h5\n\n###### h6",
  "private": true ,
  "tags": [
    {
      "name": "初心者"
    },
    {
      "name": "Qiita"
    }
  ],
  "title": "Example title",
  "tweet": false
}

###
# show articles
GET /api/v2/authenticated_user/items?page=1&per_page=20 HTTP/1.1
Host: {{host}}
Authorization: Bearer {{token}}


###
# release article
@item_id = f20db48b7282c3a35b17
PATCH /api/v2/items/{{item_id}} HTTP/1.1
Content-Type: application/json
Host: {{host}}
Authorization: Bearer {{token}}

{
  "body": "# Example",
  "coediting": false,
  "group_url_name": "dev",
  "private": true,
  "tags": [
    {
      "name": "api",
      "versions": ["_"]
    }
  ],
  "title": "Example patched"
}


###
DELETE /api/v2/items/{{item_id}} HTTP/1.1
Host: {{host}}
Authorization: Bearer {{token}}
