# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [main]
    types: [closed]

  # Update Qiita with "develop mode"
  push:
    branches: [develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update_Qiita:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # run workflow when pull-request merged
    if: github.event.pull_request.merged == true || ${{ github.ref_name }} == develop

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Install python libraries
        run: pip install -r requirements.txt

      - name: Run python script
        run: python .github/scripts/sync_qiita.py
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
          REF_NAME: ${{ github.ref_name }}
